### Prueba de registro de ciudadano
POST http://localhost:4567/register
Content-Type: application/json

{
    "email": "20200333@aloe.ulima.edu.pe",
    "password": "securepassword123",
    "first_name": "Cesar",
    "last_name": "?Contraseña1234",
    "gender": 1,
    "dni": "12345678",
    "phone_number": "987654321",
    "district": 3
}
