@token = eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MzU3NTg2MTgsImlkIjo3OSwiZW1haWwiOiJyZW56b3RpcHVsYTI3MDNAZ21haWwuY29tIiwiZmlyc3RfbmFtZSI6IkpvaG4iLCJsYXN0X25hbWUiOiJEb2UiLCJwaG90byI6Im51ZXZhX2ltYWdlbl91cmxzcyIsInJvbGUiOjJ9.UsTDS78Vi2BWmcsP9RO4PCRMINQ8eb1VN6h1fl-TIg0
@tokenadmin = eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MzM2NDQwOTIsImlkIjoxLCJlbWFpbCI6ImFkbWluQGlubGltYS5jb20iLCJmaXJzdF9uYW1lIjoiQWRtaW4iLCJsYXN0X25hbWUiOiJGb3JhbGwiLCJwaG90byI6IiIsInJvbGUiOjF9.WN5TbA1zeDisiMX3Q2SJan-F7Ab4Q6C_UJ-m3aFqzmY


### Prueba para agregar una queja
POST http://127.0.0.1:4567/complaint
Content-Type: application/json
Authorization: {{token}}

{
    "description": "Descripción de prueba de la queja",
    "location_description": "Dirección de prueba",
    "latitude": -12.04318,
    "longitude": -77.02824,
    "district": 1,
    "subject": 2,
    "photos": ["http://example.com/photo1.jpg", "http://example.com/photo2.jpg"]
}

### Prueba para encontrar la ubicación de una queja
GET http://127.0.0.1:4567/complaint/1/location
Content-Type: application/json

### Prueba para encontrar el distrito de una queja
GET http://127.0.0.1:4567/complaint/1/district
Content-Type: application/json

### Prueba para obtener quejas filtradas
POST http://localhost:4567/complaints/filtered
Authorization: {{tokenadmin}}
Content-Type: application/json

{
    "subject_ids": [1, 2],
    "districtc_ids": [1]
}


### Prueba para obtener detalles de una queja específica
GET http://127.0.0.1:4567/complaint/1/details
Content-Type: application/json

### Prueba para obtener quejas de un usuario
GET http://127.0.0.1:4567/user/complaints
Content-Type: application/json
Authorization: {{token}}

#####
POST http://127.0.0.1:4567/complaints/getfullcomplaint
Content-Type: application/json
Authorization: {{token}}

{
    "complaint_id": 1 
}