### Prueba para crear una encuesta con datos válidos
POST http://localhost:4567/create_survey
Content-Type: application/json

{
    "title": "Encuesta de Satisfacción Ciudadana",
    "description": "Evaluación de los servicios municipales",
    "photo": "https://example.com/image.jpg",
    "start_date": "2024-11-01 08:00:00",
    "end_date": "2024-12-30 08:00:00",
    "district_id": 1
}

### Prueba para crear una encuesta con una fecha de inicio futura y sin fecha de fin
GET http://localhost:4567/survey
Content-Type: application/json