### Prueba para crear un token de verificación
POST http://localhost:4567/token/create
Content-Type: application/json

{
    "email": "valentinatp@inlima.com"
}

### Prueba para verificar un token de verificación válido
POST http://localhost:4567/token/verify
Content-Type: application/json

{
    "email": "usuario@example.com",
    "code": "123456" 
}