@baseUrl = http://127.0.0.1:4567/
@token = eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE3MzM2MzU4MTIsImlkIjo3NywiZW1haWwiOiJnYWJyaWVsdGdAaW5saW1hLmNvbSIsImZpcnN0X25hbWUiOiJHYWJyaWVsIiwibGFzdF9uYW1lIjoiVG9ycmVzIEdhcmNpYSIsInBob3RvIjoiIiwicm9sZSI6Mn0.bNTKUM5vZQSN65sUqmeZ-hkRH0EJxAecO2Hc94cyR_4

######
POST http://localhost:4567/iniciar_sesion
Content-Type: application/json

{
  "email": "gabrieltg@inlima.com",
  "password": "password"
}

###########
######
POST http://localhost:4567/iniciar_sesion
Content-Type: application/json

{
  "email": "admin@inlima.com",
  "password": "password"
}

###########
PUT http://localhost:4567/actualizar_cuenta
Authorization: {{token}}
Content-Type: application/json

{
  "password": "*Renzo??SEFSASAS222A",
  "photo": "nueva_imagen_urlss"
}

#######

GET http://localhost:4567/obtener_rol
Authorization: {{token}}

######
POST http://localhost:4567/encontrar_usuario
Content-Type: application/json

{
  "citizen_id": 77
}

#########
POST http://localhost:4567/find_user_by_email
Content-Type: application/json

{
  "email": "renzotipula2703@gmail.com"
}

###########
POST http://localhost:4567/reset_password
Content-Type: application/json

{
  "email": "usuario@example.com",
  "password": "NuevaContraseñaSegura123"
}
